### PR TITLE
Raise events for drone creation so other mods can hook into it

### PR DESCRIPTION
**Pull request by TimVroom**
In the case other mods want to add/limit the amount of drones there currently is no method to easily limit the amount of drones.
With the raise events its rather easy to monitor/control the amount of drones.

### CODE REVIEW

**Comment by Klonan** [comment]
Nope, I don't want other mods interfering with my drones.

Do you have a more specific use case other than 

> other mods want to add/limit the amount of drones

**Comment by TimVroom** [comment]
Well currently i'm trying to show the amount of used/active drones in a gui. 
I tried to do an full surface scan, but that quickly ended up tanking the fps/ups. In my case it would freeze the game for a little while.

With the script_raised events its rather easy to track them. I know there is the possibility to than alter the drones and whatnot, but i didn't find another way to keep track of them.

Maybe a remote call to get_active_drones or something like that would be sufficient. But I couldn't really find a way to include that in the current way of the code, and added the script_raised events was one of the only ones that would give me what i want without messing up the code.

**Comment by Klonan** [comment]
Are you interested in the just the counts?

It makes more sense as a remote call to get the number, so then we don't have 2 mods tracking all the events and storing all the references

**Comment by TimVroom** [comment]
just the counts would be sufficient, maybe it would be great to be able to limit them to a certain amount, but since thats not a thing you want, the count should suffice :)

I'll cancel the PR then. Ty in advance!

**Pull request closed without merging**
